# Generated by Django 3.2.5 on 2022-11-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_orderitems_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpictures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_picture', to='stores.products'),
        ),
    ]
