# Generated by Django 3.2.5 on 2022-11-27 03:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_productpictures_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvaluations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('evalucount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_evaluation', to='stores.products')),
            ],
            options={
                'db_table': 'product_evaluations',
            },
        ),
        migrations.CreateModel(
            name='EvaluationCul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avarageevalu', models.PositiveSmallIntegerField()),
                ('productevaluations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_evaluationcul', to='stores.productevaluations')),
            ],
            options={
                'db_table': 'evaluation_cul',
            },
        ),
    ]
