# Generated by Django 3.2.5 on 2022-11-27 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0007_evaluationcul_productevaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='productevaluations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.users'),
            preserve_default=False,
        ),
    ]
