# Generated by Django 3.2.5 on 2022-11-27 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_evaluationcul_productevaluations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcul',
            name='productevaluations',
        ),
        migrations.AddField(
            model_name='evaluationcul',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.products'),
            preserve_default=False,
        ),
    ]
