# Generated by Django 3.2.5 on 2022-11-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20221127_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcul',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_evaluationcul', to='stores.products'),
        ),
    ]
