# Generated by Django 3.2.5 on 2022-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_alter_evaluationcul_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcul',
            name='avarageevalu',
            field=models.FloatField(),
        ),
    ]
