# Generated by Django 3.2.5 on 2022-12-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_alter_evaluationcul_avarageevalu'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product_type', to='stores.producttypes'),
        ),
    ]
