# Generated by Django 3.2.5 on 2022-12-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_auto_20221214_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='ChekeoutPrice',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ChekeoutProduct',
        ),
    ]
