# Generated by Django 3.2.5 on 2022-12-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_auto_20221214_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='chekeoutproduct',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_checkoutproduct', to='stores.products'),
            preserve_default=False,
        ),
    ]
