# Generated by Django 3.2.5 on 2022-12-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_chekeoutproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='chekeoutprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.chekeoutproduct'),
        ),
    ]
