# Generated by Django 3.2.5 on 2023-01-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_auto_20221221_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chekeoutprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product_id', to='stores.chekeoutproduct'),
        ),
        migrations.AlterField(
            model_name='chekeoutproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.products'),
        ),
    ]
