# Generated by Django 3.2.5 on 2023-01-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_auto_20230104_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='productevaluations',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
