# Generated by Django 3.2.5 on 2023-01-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_productevaluations_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcul',
            name='product_evalu',
        ),
    ]
