# Generated by Django 3.2.5 on 2023-01-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_remove_evaluationcul_product_evalu'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcul',
            name='product_evalu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_evalu_col', to='stores.productevaluations'),
            preserve_default=False,
        ),
    ]
